apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpg-awesome-icons
  namespace: triangular
spec:
  selector:
    matchLabels:
      app: rpg-awesome-icons
  replicas: 1
  template:
    metadata:
      labels:
        app: rpg-awesome-icons
    spec:
      containers:
      - name: rpg-awesome-icons-example-app
        image: registry.akehir.com:443/triangular/password-checker/password-checker-example-app:develop-4546039f-1715602500 # {"$imagepolicy": "triangular:password-checker-example-app-image-policy"}
        imagePullPolicy: Always
        ports:
        - containerPort: 8811
      imagePullSecrets:
      - name: deploy-triangular
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
