---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: triangular-rpg-awesome-icons-image-repository
  namespace: triangular
spec:
  image: registry.akehir.com:443/triangular/rpg-awesome-icons/rpg-awesome-icons-example-app
  interval: 5m
  secretRef:
    name: deploy-triangular
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rpg-awesome-icons-example-app-image-policy
  namespace: triangular
spec:
  imageRepositoryRef:
    name: triangular-rpg-awesome-icons-image-repository
  filterTags:
    pattern: '^develop-[a-fA-F0-9]+-(?P<ts>[1-9][0-9]*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: triangular-rpg-awesome-icons-image-update-automation
  namespace: triangular
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: triangular-rpg-awesome-icons-git
  git:
    checkout:
      ref:
        branch: develop
    commit:
      author:
        email: mr.robot@akehir.com
        name: mr.robot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: develop
  update:
    path: ./manifests
    strategy: Setters
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: triangular-rpg-awesome-icons-git
  namespace: triangular
spec:
  interval: 1m0s
  ref:
    branch: develop
  url: https://git.akehir.com/triangular/rpg-awesome-icons.git
  secretRef:
    name: triangular-mr-robot
---
