import { Component, ViewEncapsulation } from '@angular/core';
import { RpgAwesomeIconsRegistry, } from '@triangular/rpg-awesome-icons';

import {
  rpgAwesomeIconCampfire,
  rpgAwesomeIconCancel,
  rpgAwesomeIconCancer,
  rpgAwesomeIconCandleFire,
  rpgAwesomeIconCandle,
  rpgAwesomeIconCannonShot,
  rpgAwesomeIconCapitol,
  rpgAwesomeIconCapricorn,
  rpgAwesomeIconCarrot,
  rpgAwesomeIconCastleEmblem,
  rpgAwesomeIconCastleFlag,
  rpgAwesomeIconCat,
  rpgAwesomeIconChain,
  rpgAwesomeIconCheese,
  rpgAwesomeIconChemicalArrow,
  rpgAwesomeIconChessboard,
  rpgAwesomeIconChickenLeg,
  rpgAwesomeIconCircleOfCircles,
  rpgAwesomeIconCircularSaw,
  rpgAwesomeIconCircularShield,
  rpgAwesomeIconCloakAndDagger,
  rpgAwesomeIconClockwork,
  rpgAwesomeIconClover,
  rpgAwesomeIconCloversCard,
  rpgAwesomeIconClovers,
  rpgAwesomeIconClusterBomb,
  rpgAwesomeIconCoffeeMug,
  rpgAwesomeIconCogWheel,
  rpgAwesomeIconCog,
  rpgAwesomeIconColdHeart,
  rpgAwesomeIconCompass,
  rpgAwesomeIconCorkedTube,
  rpgAwesomeIconCrabClaw,
  rpgAwesomeIconCrackedHelm,
  rpgAwesomeIconCrackedShield,
  rpgAwesomeIconCrocSword,
  rpgAwesomeIconCrossbow,
  rpgAwesomeIconCrossedAxes,
  rpgAwesomeIconCrossedBones,
  rpgAwesomeIconCrossedPistols,
  rpgAwesomeIconCrossedSabres,
  rpgAwesomeIconCrossedSwords,
  rpgAwesomeIconCrownOfThorns,
  rpgAwesomeIconCrown,
  rpgAwesomeIconCrownedHeart,
  rpgAwesomeIconCrush,
  rpgAwesomeIconCrystalBall,
  rpgAwesomeIconCrystalCluster,
  rpgAwesomeIconCrystalWand,
  rpgAwesomeIconCrystals,
  rpgAwesomeIconCubes,
  rpgAwesomeIconCutPalm,
  rpgAwesomeIconCycle,
} from '@triangular/rpg-awesome-icons/icons';

// eslint-disable-next-line @angular-eslint/prefer-standalone
@Component({
  selector: 'app-icons-c',
  templateUrl: './icons-c.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  standalone: false
})
export class IconsCComponent {
  icons = [
    rpgAwesomeIconCampfire,
    rpgAwesomeIconCancel,
    rpgAwesomeIconCancer,
    rpgAwesomeIconCandleFire,
    rpgAwesomeIconCandle,
    rpgAwesomeIconCannonShot,
    rpgAwesomeIconCapitol,
    rpgAwesomeIconCapricorn,
    rpgAwesomeIconCarrot,
    rpgAwesomeIconCastleEmblem,
    rpgAwesomeIconCastleFlag,
    rpgAwesomeIconCat,
    rpgAwesomeIconChain,
    rpgAwesomeIconCheese,
    rpgAwesomeIconChemicalArrow,
    rpgAwesomeIconChessboard,
    rpgAwesomeIconChickenLeg,
    rpgAwesomeIconCircleOfCircles,
    rpgAwesomeIconCircularSaw,
    rpgAwesomeIconCircularShield,
    rpgAwesomeIconCloakAndDagger,
    rpgAwesomeIconClockwork,
    rpgAwesomeIconClover,
    rpgAwesomeIconCloversCard,
    rpgAwesomeIconClovers,
    rpgAwesomeIconClusterBomb,
    rpgAwesomeIconCoffeeMug,
    rpgAwesomeIconCogWheel,
    rpgAwesomeIconCog,
    rpgAwesomeIconColdHeart,
    rpgAwesomeIconCompass,
    rpgAwesomeIconCorkedTube,
    rpgAwesomeIconCrabClaw,
    rpgAwesomeIconCrackedHelm,
    rpgAwesomeIconCrackedShield,
    rpgAwesomeIconCrocSword,
    rpgAwesomeIconCrossbow,
    rpgAwesomeIconCrossedAxes,
    rpgAwesomeIconCrossedBones,
    rpgAwesomeIconCrossedPistols,
    rpgAwesomeIconCrossedSabres,
    rpgAwesomeIconCrossedSwords,
    rpgAwesomeIconCrownOfThorns,
    rpgAwesomeIconCrown,
    rpgAwesomeIconCrownedHeart,
    rpgAwesomeIconCrush,
    rpgAwesomeIconCrystalBall,
    rpgAwesomeIconCrystalCluster,
    rpgAwesomeIconCrystalWand,
    rpgAwesomeIconCrystals,
    rpgAwesomeIconCubes,
    rpgAwesomeIconCutPalm,
    rpgAwesomeIconCycle,
  ];

  constructor(private registry: RpgAwesomeIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
