import { Component, ViewEncapsulation } from '@angular/core';
import { RpgAwesomeIconsRegistry, } from '@triangular/rpg-awesome-icons';

import {
  rpgAwesomeIconBall,
  rpgAwesomeIconBarbedArrow,
  rpgAwesomeIconBarrier,
  rpgAwesomeIconBatSword,
  rpgAwesomeIconBatteredAxe,
  rpgAwesomeIconBatteries,
  rpgAwesomeIconBattery0,
  rpgAwesomeIconBattery100,
  rpgAwesomeIconBattery25,
  rpgAwesomeIconBattery50,
  rpgAwesomeIconBattery75,
  rpgAwesomeIconBatteryBlack,
  rpgAwesomeIconBatteryNegative,
  rpgAwesomeIconBatteryPositive,
  rpgAwesomeIconBatteryWhite,
  rpgAwesomeIconBatwings,
  rpgAwesomeIconBeamWake,
  rpgAwesomeIconBearTrap,
  rpgAwesomeIconBeer,
  rpgAwesomeIconBeetle,
  rpgAwesomeIconBell,
  rpgAwesomeIconBiohazard,
  rpgAwesomeIconBirdClaw,
  rpgAwesomeIconBirdMask,
  rpgAwesomeIconBladeBite,
  rpgAwesomeIconBlast,
  rpgAwesomeIconBlaster,
  rpgAwesomeIconBleedingEye,
  rpgAwesomeIconBleedingHearts,
  rpgAwesomeIconBoltShield,
  rpgAwesomeIconBombExplosion,
  rpgAwesomeIconBombs,
  rpgAwesomeIconBoneBite,
  rpgAwesomeIconBoneKnife,
  rpgAwesomeIconBook,
  rpgAwesomeIconBoomerang,
  rpgAwesomeIconBootStomp,
  rpgAwesomeIconBottleVapors,
  rpgAwesomeIconBottledBolt,
  rpgAwesomeIconBottomRight,
  rpgAwesomeIconBowieKnife,
  rpgAwesomeIconBowlingPin,
  rpgAwesomeIconBrainFreeze,
  rpgAwesomeIconBrandyBottle,
  rpgAwesomeIconBridge,
  rpgAwesomeIconBroadheadArrow,
  rpgAwesomeIconBroadsword,
  rpgAwesomeIconBrokenBone,
  rpgAwesomeIconBrokenBottle,
  rpgAwesomeIconBrokenHeart,
  rpgAwesomeIconBrokenShield,
  rpgAwesomeIconBrokenSkull,
  rpgAwesomeIconBubblingPotion,
  rpgAwesomeIconBullets,
  rpgAwesomeIconBurningBook,
  rpgAwesomeIconBurningEmbers,
  rpgAwesomeIconBurningEye,
  rpgAwesomeIconBurningMeteor,
  rpgAwesomeIconBurstBlob,
  rpgAwesomeIconButterfly,
} from '@triangular/rpg-awesome-icons/icons';

/* eslint-disable @angular-eslint/prefer-standalone */
@Component({
  selector: 'app-icons-b',
  templateUrl: './icons-b.component.html',
  styleUrls: [],
  encapsulation: ViewEncapsulation.None,
  standalone: false
})
export class IconsBComponent {
  icons = [
    rpgAwesomeIconBall,
    rpgAwesomeIconBarbedArrow,
    rpgAwesomeIconBarrier,
    rpgAwesomeIconBatSword,
    rpgAwesomeIconBatteredAxe,
    rpgAwesomeIconBatteries,
    rpgAwesomeIconBattery0,
    rpgAwesomeIconBattery100,
    rpgAwesomeIconBattery25,
    rpgAwesomeIconBattery50,
    rpgAwesomeIconBattery75,
    rpgAwesomeIconBatteryBlack,
    rpgAwesomeIconBatteryNegative,
    rpgAwesomeIconBatteryPositive,
    rpgAwesomeIconBatteryWhite,
    rpgAwesomeIconBatwings,
    rpgAwesomeIconBeamWake,
    rpgAwesomeIconBearTrap,
    rpgAwesomeIconBeer,
    rpgAwesomeIconBeetle,
    rpgAwesomeIconBell,
    rpgAwesomeIconBiohazard,
    rpgAwesomeIconBirdClaw,
    rpgAwesomeIconBirdMask,
    rpgAwesomeIconBladeBite,
    rpgAwesomeIconBlast,
    rpgAwesomeIconBlaster,
    rpgAwesomeIconBleedingEye,
    rpgAwesomeIconBleedingHearts,
    rpgAwesomeIconBoltShield,
    rpgAwesomeIconBombExplosion,
    rpgAwesomeIconBombs,
    rpgAwesomeIconBoneBite,
    rpgAwesomeIconBoneKnife,
    rpgAwesomeIconBook,
    rpgAwesomeIconBoomerang,
    rpgAwesomeIconBootStomp,
    rpgAwesomeIconBottleVapors,
    rpgAwesomeIconBottledBolt,
    rpgAwesomeIconBottomRight,
    rpgAwesomeIconBowieKnife,
    rpgAwesomeIconBowlingPin,
    rpgAwesomeIconBrainFreeze,
    rpgAwesomeIconBrandyBottle,
    rpgAwesomeIconBridge,
    rpgAwesomeIconBroadheadArrow,
    rpgAwesomeIconBroadsword,
    rpgAwesomeIconBrokenBone,
    rpgAwesomeIconBrokenBottle,
    rpgAwesomeIconBrokenHeart,
    rpgAwesomeIconBrokenShield,
    rpgAwesomeIconBrokenSkull,
    rpgAwesomeIconBubblingPotion,
    rpgAwesomeIconBullets,
    rpgAwesomeIconBurningBook,
    rpgAwesomeIconBurningEmbers,
    rpgAwesomeIconBurningEye,
    rpgAwesomeIconBurningMeteor,
    rpgAwesomeIconBurstBlob,
    rpgAwesomeIconButterfly,
  ];

  constructor(private registry: RpgAwesomeIconsRegistry) {
    registry.registerIcons(this.icons);
  }

}
